apiVersion: v1
kind: ConfigMap
metadata:
  name: petshop-config
  namespace: petshop-demo
data:
  # Database configuration
  POSTGRES_HOST: "postgresql-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "petshop"
  
  # Redis configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # ADOT Collector configuration
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://adot-collector:4317"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  
  # Service URLs for internal communication
  CATALOG_SERVICE_URL: "http://catalog-service:8001"
  CART_SERVICE_URL: "http://cart-service:8002"
  CHECKOUT_SERVICE_URL: "http://checkout-service:8003"
  FEATURE_FLAG_SERVICE_URL: "http://feature-flag-service:8004"
  
  # OpenTelemetry configuration
  OTEL_SERVICE_NAME: "petshop-service"
  OTEL_TRACES_SAMPLER: "always_on"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_LOGS_EXPORTER: "otlp"
  
  # Application configuration
  NODE_ENV: "production"
  LOG_LEVEL: "info"
