apiVersion: v1
kind: ServiceAccount
metadata:
  name: adot-collector
  namespace: petshop-demo
  annotations:
    # IRSA annotation - replace with your IAM role ARN
    # eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/petshop-adot-collector-role
    eks.amazonaws.com/role-arn: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: petshop-services
  namespace: petshop-demo
  annotations:
    # Optional: Add IRSA for services if they need direct AWS access
    # eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/petshop-services-role
    eks.amazonaws.com/role-arn: ""
