apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: petshop-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      serviceAccountName: petshop-services
      containers:
        - name: catalog-service
          image: ${CATALOG_IMAGE}
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
              name: http
          env:
            - name: PORT
              value: "8001"
            - name: OTEL_SERVICE_NAME
              value: "catalog-service"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=catalog-service,service.namespace=petshop-demo"
          envFrom:
            - configMapRef:
                name: petshop-config
            - secretRef:
                name: petshop-secrets
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: petshop-demo
spec:
  selector:
    app: catalog-service
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
  type: ClusterIP
