apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: petshop-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      serviceAccountName: petshop-services
      containers:
      - name: cart-service
        image: petshop/cart-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8002
          name: http
        env:
        - name: PORT
          value: "8002"
        - name: OTEL_SERVICE_NAME
          value: "cart-service"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=cart-service,service.namespace=petshop-demo"
        envFrom:
        - configMapRef:
            name: petshop-config
        - secretRef:
            name: petshop-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: petshop-demo
spec:
  selector:
    app: cart-service
  ports:
  - port: 8002
    targetPort: 8002
    protocol: TCP
  type: ClusterIP
