apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-service
  namespace: petshop-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkout-service
  template:
    metadata:
      labels:
        app: checkout-service
    spec:
      serviceAccountName: petshop-services
      containers:
      - name: checkout-service
        image: petshop/checkout-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8003
          name: http
        env:
        - name: PORT
          value: "8003"
        - name: OTEL_SERVICE_NAME
          value: "checkout-service"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=checkout-service,service.namespace=petshop-demo"
        envFrom:
        - configMapRef:
            name: petshop-config
        - secretRef:
            name: petshop-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-service
  namespace: petshop-demo
spec:
  selector:
    app: checkout-service
  ports:
  - port: 8003
    targetPort: 8003
    protocol: TCP
  type: ClusterIP
