apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-flag-service
  namespace: petshop-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feature-flag-service
  template:
    metadata:
      labels:
        app: feature-flag-service
    spec:
      serviceAccountName: petshop-services
      containers:
      - name: feature-flag-service
        image: petshop/feature-flag-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8004
          name: http
        env:
        - name: PORT
          value: "8004"
        - name: OTEL_SERVICE_NAME
          value: "feature-flag-service"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=feature-flag-service,service.namespace=petshop-demo"
        envFrom:
        - configMapRef:
            name: petshop-config
        - secretRef:
            name: petshop-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8004
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: feature-flag-service
  namespace: petshop-demo
spec:
  selector:
    app: feature-flag-service
  ports:
  - port: 8004
    targetPort: 8004
    protocol: TCP
  type: ClusterIP
