apiVersion: v1
kind: Secret
metadata:
  name: petshop-secrets
  namespace: petshop-demo
type: Opaque
stringData:
  # These values should be updated before deployment
  # Or use AWS Secrets Manager / Parameter Store integration
  POSTGRES_USER: "petshop"
  POSTGRES_PASSWORD: "REPLACE_WITH_DB_PASSWORD"
