apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: petshop-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: petshop-services
      containers:
      - name: frontend
        image: 590183851389.dkr.ecr.us-east-2.amazonaws.com/petshop-demo/frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: VITE_CATALOG_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: petshop-config
              key: CATALOG_SERVICE_URL
        - name: VITE_CART_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: petshop-config
              key: CART_SERVICE_URL
        - name: VITE_CHECKOUT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: petshop-config
              key: CHECKOUT_SERVICE_URL
        - name: VITE_FEATURE_FLAG_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: petshop-config
              key: FEATURE_FLAG_SERVICE_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: petshop-demo
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: petshop-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
