apiVersion: v1
kind: ConfigMap
metadata:
  name: adot-collector-config
  namespace: petshop-demo
data:
  adot-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    
    processors:
      batch:
        timeout: 10s
        send_batch_size: 1024
      
      memory_limiter:
        check_interval: 1s
        limit_mib: 512
      
      resourcedetection/eks:
        detectors: [env, eks]
        timeout: 2s
    
    exporters:
      awsxray:
        region: ${AWS_REGION}
      
      awsemf:
        region: ${AWS_REGION}
        namespace: PetshopDemo
        log_group_name: /aws/ecs/petshop-demo/metrics
      
      awscloudwatchlogs:
        region: ${AWS_REGION}
        log_group_name: /aws/eks/petshop-demo/services
        log_stream_name: "petshop-services"
    
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, resourcedetection/eks, batch]
          exporters: [awsxray]
        
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, resourcedetection/eks, batch]
          exporters: [awsemf]
        
        logs:
          receivers: [otlp]
          processors: [memory_limiter, resourcedetection/eks, batch]
          exporters: [awscloudwatchlogs]
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: adot-collector
  namespace: petshop-demo
spec:
  selector:
    matchLabels:
      app: adot-collector
  template:
    metadata:
      labels:
        app: adot-collector
    spec:
      serviceAccountName: adot-collector
      containers:
      - name: adot-collector
        image: public.ecr.aws/aws-observability/aws-otel-collector:latest
        command:
          - "/awscollector"
          - "--config=/conf/adot-config.yaml"
        env:
        - name: AWS_REGION
          value: "us-east-2"
        ports:
        - containerPort: 4317  # OTLP gRPC
          protocol: TCP
        - containerPort: 4318  # OTLP HTTP
          protocol: TCP
        volumeMounts:
        - name: adot-config
          mountPath: /conf
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: adot-config
        configMap:
          name: adot-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: adot-collector
  namespace: petshop-demo
spec:
  selector:
    app: adot-collector
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
    protocol: TCP
  - name: otlp-http
    port: 4318
    targetPort: 4318
    protocol: TCP
  type: ClusterIP
